---
- name: Install Updates
  hosts: all
  serial: 1
  tasks:

  # One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
  - name: Ensure WinRM starts when the system has settled and is ready to work reliably
    win_service:
      name: WinRM
      start_mode: delayed

  - name: Install all security updates with automatic reboots
    win_updates:
      category_names:
      - SecurityUpdates
      reboot: yes
      reboot_timeout: 3600
